name: filecoin_address
description: Filecoin address utils, suport all address types.
version: 1.1.0
repository: https://github.com/stonega/filecoin_address

environment:
  sdk: '>=2.19.6 <4.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  base32: ^2.1.3
  hashlib: ^1.11.4
  leb128: ^1.1.0
